### ISSUE TITLE
HTTP request failed: The requested URL returned error: 401

### ISSUE THREAD

**Issue by Megumiiiiii** [heshuchao/space-mining-guide#2]
![Screenshot_35](https://user-images.githubusercontent.com/98658943/200606820-edadef3e-e941-4d8b-98b2-059abf92fe29.png)

**Comment by Brochao** [comment]
Did you replace the  `-O user:password` that matches your configurations in mvc.conf?

**Comment by Megumiiiiii** [comment]
Yes ,,after that i got error: 500

**Comment by Brochao** [comment]
Please make sure your node is running properly or not

**Comment by Megumiiiiii** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/98658943/201493007-9871950c-a747-428c-a6cc-8b5d366db307.png)
New Problem ,,,how to stop and completely remove node ? so i can restart from 0

**Comment by heshuchao** [comment]
use `mvc-cli  stop` to stop the node.

If you want to restart sync, delete the blocks directory in your node_data_dir.

**Comment by Megumiiiiii** [comment]
Alright

**Comment by heshuchao** [comment]
> ![image](https://user-images.githubusercontent.com/34889287/201940872-672232fc-76eb-4fef-9187-fe6388644051.png)
> "json_rpc_call failed, retry after 30 seconds" i got this

try `mvc-cli getblocktemplate` please

**Comment by dinarsanjaya** [comment]
> mvc-cli getblocktemplate

![image](https://user-images.githubusercontent.com/34889287/201996976-5e7fccef-b039-4add-b676-bb0ba3dfd40f.png)
like this
